# Generated by Django 4.0.5 on 2022-06-16 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_article_category'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='article',
            table=None,
        ),
        migrations.AlterModelTable(
            name='category',
            table=None,
        ),
    ]
